### DISCUSSION TITLE
Setting volume for TTS

### DISCUSSION THREAD

**Discussion by szaske** [alandtse/alexa_media_player#1347] [Q&A]
Thank you for this great Alexa Integration. I'm using it to alert me when a person is detected in my front yard using the also excellent Frigate NVR. One question though, is there a way to set the volume of the TTS notification? I've tried sending volume_level in the data object, but no luck.

```
{
    "message": "A person is detected in the driveway",
    "data": {
        "type": "tts",
        "volume_level": 0.2
    }
}
```
Is there a way to accomplish this?

**Comment by pedolsky** [comment]
That would be interesting to learn. Personally I only know the two-part way:

```
    - service: media_player.volume_set
      target:
        entity_id: group.echos
      data:
        volume_level: 1

    - service: notify.alexa_media
      data:
        message: Alarm
        target: group.echos
        data:
          type: tts
          method: speak
```
