### DISCUSSION TITLE
Can I send a custom command with alexa's responce whispered or muted

### DISCUSSION THREAD

**Discussion by Kurisudes** [alandtse/alexa_media_player#1560] [Q&A]
Hello all,
I use alexa at night when with a custom command to play an audio book. My wife is offen already sleeping and wakes up by alexa's responce. 
Is there a way to mute, omit or at least whisper the responce?

I tried setting the volume to 0 and adding <amazon:effect name="whispered"> to the command but it doesn't work. 
```
service: media_player.play_media
target:
  entity_id: media_player.guest_room
data:
  media_content_type: custom
  media_content_id: 'play Der kleine Bruder on Audible'
```
I hope somebody can help.
