### DISCUSSION TITLE
"play artist XYZ on Amazon Music" only working every other call?

### DISCUSSION THREAD

**Discussion by ThijmenDam** [alandtse/alexa_media_player#1743] [General]
Is anyone familiar with the issue that a call to play some music on an Echo Dot works only every other call?

For example, consider the following service:

```
service: media_player.play_media
data:
  entity_id: media_player.tammo_s_echo_dot
  media_content_id: john mayer
  media_content_type: AMAZON_MUSIC
  extra:
    timer: 10
```

The first time I call this service, the Echo Dot responds with "Here's some music by John Mayer on Amazon Music" and it starts playing music just fine. However, when I call this service a second time, the Echo Dot does respond with the same message but the music does not start playing. When I call the service for a third time, I get the proper response but now the music does start paying. And so on. Anyone has an idea what might be going on? 

NB: I noticed the same behaviour also happens when I directly ask the Echo Dot, i.e. without AMP in between.
