### DISCUSSION TITLE
Phone notifications stopped working

### DISCUSSION THREAD

**Discussion by molnarti** [alandtse/alexa_media_player#1757] [Q&A]
So I've been using this service to get a notification on my phone via the alexa app in case a door was opened in my house while me and my wife ware away so i could immedately drop in on my echo speaker via the alexa app on my phone and talk to the intruder

```
service: notify.alexa_media
data:
  target: media_player.tibors_echo
  data:
    type: dropin_notification
  message: >-
    {{ trigger.to_state.attributes.friendly_name }} opened at    
    {{now().strftime("%Y-%m-%d %H:%M")}}
```

However the notification stopped appearing on my new phone, even though it triggers a notification on my iPad where i use the same login. App notifications are enabled both on the android system as well as the alexa app.  I cannot figure out what is wrong, probably some obscure setting in the alexa app itself. The Echo device can be seen in the app. What else it can be?
