### DISCUSSION TITLE
Alert integration with custom-components / alexa_media_player

### DISCUSSION THREAD

**Discussion by huuscript** [alandtse/alexa_media_player#1758] [Show and tell]
Since I already have this [custom-components / alexa_media_player](https://github.com/custom-components/alexa_media_player) I have been searching everywhere how to get the [Alert](https://www.home-assistant.io/integrations/alert/) integration to work with the it to get Alexa to announce the alert.
In the end through trial and error i stumble across a solution, it’s a lot easier than I thought. I would like to share it here and hope it useful to someone. Let me know if it already covered elsewhere.
This assumes you have the alexa_media_player custom component install and working already.

All you need to do is add these to your configuration.yaml
This will get Alexa to say “front door is open” every 1 minute that the door sensor is in the “on” state

```
alert:
  front_door:
    name: Front door is open
    done_message: Front door is now closed
    entity_id: binary_sensor.door_window_sensor
    state: "on"
    repeat: 1
    can_acknowledge: true
    skip_first: true
    data:
      message:
    notifiers:
      - alexa_media_name
```
    
That it, no need to define notify integration as the service notify.alexa_media_name for each echo is already created from the alexa_media component. The extra lines that make it work is

    data:
      message:
