### DISCUSSION TITLE
Difficult to switch account to listen to other Spotify account

### DISCUSSION THREAD

**Discussion by Kurisudes** [alandtse/alexa_media_player#1785] [Q&A]
Hey all, 

I found a solution for my problem but it is not nice and it took me a long time to figure it out.
Therefore, I want to share my solution and ask you whether you know a better one.

We have two accounts signed in to the Alexa media player to be able to play both our Spotify accounts. Now switching between to a specific account is quite difficult and needs multiple commands. I don't want to do it like a stone-age-human with voice commands.

Then I created two buttons and the automation which you can see below.

The not so nice thing is.
1. It is very slow
2. It seams to sometimes switch to the wrong account but in 9 out of 10 it works

Do you have a better solution.

```
alias: Spotify Control
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.spotify_switch_to_sayakas_account
    id: Saya
  - platform: state
    entity_id:
      - input_button.spotify_switch_to_chris_account
    id: Chris
condition: []
action:
  - if:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: Chris
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.echo_studio_2',
                  'media_position_updated_at') >=
                  state_attr('media_player.echo_studio',
                  'media_position_updated_at')}}
          - condition: and
            conditions:
              - condition: trigger
                id: Saya
              - condition: template
                value_template: >-
                  {{ state_attr('media_player.echo_studio',
                  'media_position_updated_at') >=
                  state_attr('media_player.echo_studio_2',
                  'media_position_updated_at')}}
    then:
      - service: media_player.play_media
        data:
          media_content_type: custom
          media_content_id: switch account
        target:
          entity_id:
            - media_player.echo_studio_2
            - media_player.echo_studio
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
      - service: media_player.media_stop
        data: {}
        target:
          entity_id:
            - media_player.echo_studio_2
            - media_player.echo_studio
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
  - repeat:
      until:
         - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: Chris
                  - condition: state
                    entity_id: media_player.echo_studio
                    state: playing
              - condition: and
                conditions:
                  - condition: trigger
                    id: Saya
                  - condition: state
                    entity_id: media_player.echo_studio_2
                    state: playing
      sequence:
        - service: media_player.play_media
          data:
            media_content_type: custom
            media_content_id: play spotify
          target:
            entity_id:
              - media_player.echo_studio_2
              - media_player.echo_studio
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
mode: single
```

Additionally, I alway have to give media_player.echo_studio_2 and media_player.echo_studio as target. This is the same device but associated with the different accounts. If I only specify one. Then it sometimes works and sometimes not.
