### DISCUSSION TITLE
Problem with notify and play_media not working for all devices

### DISCUSSION THREAD

**Discussion by MarkL1969** [alandtse/alexa_media_player#2100] [Q&A] [answered]
Hi there,

I'm a newbie and I'm trying to gather everything I need to set up automations. TTS / notifications to my alexa echos and alexa sonos is of course a major part in this.

HA and Alexa Media Player setup and running current versions.

In this case I'm using notify with "announce" type to a couple of devices:

```
service: notify.alexa_media
data:
  message: Testnachricht
  data:
    type: announce
  target:
    - media_player.echo_wc
    - media_player.echo_bad
    - media_player.echo_jonas
    - media_player.sonos_arc
    - media_player.sonos_move_2
```

Most of them do play the message - but not all of them!
In this example, I don't get a notification on media_player.sonos_move_2, even so the device is working and I can control this entity using the HA player UI.
I do have a problem with another sonos devices, controlled by alexa. So all echos do work, one Sonos does work too (arc) two Sonos don't work (Move and One)

The problem is the same when using `play_media`...

I can't find the reason (for 2 days now).
Any help would be highly appreciated!

Best 
Mark
