### DISCUSSION TITLE
Passing input text / select to echo device as 'custom'

### DISCUSSION THREAD

**Discussion by zav13r** [alandtse/alexa_media_player#2211] [Q&A]
Hi everyone,

Looking for some help from those more knowledgeable than me.. I am trying to setup a UI for sending music requests with input text and input select, for room, group etc. Similar to Sonos for multi room music from a central tablet. All integrations are setup and working well. What I am struggling with is passing the input text value correctly using alexa service calls.

I have a script:

```
echo_music_room:
  alias: Play Music in room
  sequence:
  - service: media_player.play_media
    data_template:
      entity_id: media_player.living_room_echo
      media_content_id: play {{name_of_music}} on {{room_name}} echo on amazon music
      media_content_type: custom
  mode: single
  icon: mdi:music
```
And in lovelace, have the following:

```
type: vertical-stack
cards:
  - type: entity
    entity: input_text.music_to_play
    state_color: false
    name: What to play?
  - type: entity
    entity: input_select.music_room
    name: Where?
  - type: custom:mini-media-player
    entity: media_player.living_room_echo
    icon: mdi:amazon
    artwork: cover
    shortcuts:
      columns: 1
      buttons:
        - icon: mdi:play
          name: Play
          type: service
          id: script.echo_music_room
          data:
            name_of_music: '{{ states(''input_text.music_to_play'') }}'
            room_name: '{{ states(''input_select.music_room'') }}'
    sound_mode: icon
```
I have also tried as a button, rather than media player card, with the same result.

What I hoped to achieve was a free text input for the music to play, and a dropdown of where to play. The input selects are set up correctly, but the issue is how the data is received by Alexa. The voice response I get is 'Could not find a device named music room', so it is sending the input_select name, rather than the selected state.

Where am I going wrong?

Thank you
