### DISCUSSION TITLE
Use Multiple Echo Dot's as Alarmo Siren

### DISCUSSION THREAD

**Discussion by jparker80** [alandtse/alexa_media_player#2263] [Q&A]
I'll start by saying I'm brand new to Home Assistant (been using it about a week) and pretty new to yaml in general so I apologize if I'm missing something obvious.

Issue: Added 2nd Echo Dot to act as additional "siren" for my Alarmo setup and cannot get it to repeat the audio clip on both at same time, but works fine when set to 1 Dot (hope that makes sense?)

Here's the yaml, when set to only deliver the script to the "Living Room Dot" it works and the sound repeats multiple times, once I add the Bedroom Dot into the mix, they both only play the sound once.

Basic operation is when Alarmo is triggered it turns the volume to 100% on the dot(s) and then plays a 5 second audio clip 5 times and then turns the dot(s) volume back to 40%

Any ideas on how to get this to work on both dots? Thank you in advance!

```
alias: Alarm Siren (NEW)
description: ""
trigger:
  - platform: device
    device_id: a051bb3255b2d44cf4b42119394982a8
    domain: alarm_control_panel
    entity_id: 40ed08eacb7a1924759e0f3cdde1b346
    type: triggered
condition: []
action:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 1
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
  - service: media_player.play_media
    metadata: {}
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_scifi_alarm_01
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
  - service: media_player.play_media
    metadata: {}
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_scifi_alarm_01
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
  - service: media_player.play_media
    metadata: {}
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_scifi_alarm_01
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
  - service: media_player.play_media
    metadata: {}
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_scifi_alarm_01
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
  - service: media_player.play_media
    metadata: {}
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_scifi_alarm_01
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.4
    target:
      device_id:
        - dcc74614ef7cbee401e18d893e734b36
        - faab1be8dbbd1ebad3f46bfece39df09
mode: single
```
