### DISCUSSION TITLE
ask alexa for the temperate of a device

### DISCUSSION THREAD

**Discussion by JamieP83** [alandtse/alexa_media_player#2298] [Q&A]
Hey all,
i have a sensor = sensor.hotwater_temperature_tracker
that is created via this device:

```
      hotwater_temperature_tracker:
        friendly_name: "Hot Water Temp"
        unit_of_measurement: "°C"
        value_template: "{{state_attr('water_heater.vicare_water', 'current_temperature') }}"
```

which is passed to Alexa as:

```
      sensor.hotwater_temperature_tracker:
        display_categories: TEMPERATURE_SENSOR
        name: Hot Water Temperature
```

So i can see this in Alexa.
however if i ask alexa "Whats the hot water temperate" it says "hot water doesnt support that"

what am i doing wrong?
