### DISCUSSION TITLE
Alexa Media Invalid Config

### DISCUSSION THREAD

**Discussion by ArtJustine** [alandtse/alexa_media_player#2551] [Q&A]
Can someone help me with this? 

I tried removing the integration, re-install it through HACS, and the same error message pops up.

![Screenshot 2024-09-21 174459](https://github.com/user-attachments/assets/d590e26c-a1e5-4f09-a47b-2dfbc2977c01)

**Comment by Alerico02** [comment]
Got the same problem because proxy login is not working (it gos in loop without working).
I solved putting the configuration like this:

```
media_player:
  - platform: alexa
    email: “your amazon email”
    password: “your amazon password”
    url: “amazon.com”
``` 

**BUT STILL NOT WORKING**, The notification is gone but the integration and the devices don't show up.

Also normal configuration don't show "legacy"option.

![immagine_2024-09-21_182507352](https://github.com/user-attachments/assets/506e48b7-0533-4009-b971-036ace61d1aa)
(sorry for language)

Can someone explain the installation procedure? Maybe we left something....
