### DISCUSSION TITLE
Notification and Echo Show 8

### DISCUSSION THREAD

**Discussion by marsal-75** [alandtse/alexa_media_player#2564] [Q&A]
Only on the Echo Show 8, the text sent via the notify.alexa_media service has not been played for several days (it only appears on the screen), yet the command has always worked. Has anyone who has had the same problem managed to fix it?
Here the command working on other echo devices:
```
data:
  target: media_player.echo_show_salone
  data:
    type: announce
  message: Test message
action: notify.alexa_media
```
Thank you in advance.
