### DISCUSSION TITLE
notify service

### DISCUSSION THREAD

**Discussion by ae8u** [alandtse/alexa_media_player#2669] [Q&A]
I have installed and reinstalled the app several times. But I do not have the notify.media_player, nor the tts.say service.

How do I get those two services? I have already tried to add them via yaml file without success. 

Thanks,
Mike

**Comment by danielbrunt57** [comment]
The `alexa_media` `notify` service is `notify.alexa_media` as well as ones for each of your included echo devices
e.g. `notify.alexa_media_bedroom_echo_dot_left`, as well as `notify.alexa_media_last_called`.

Other services it adds are:
`alexa_media.force_logout`, `alexa_media.update_last_called`

The `media_player` services are:
`media_player.clear_playlist`
`media_player.join`
`media_player.media_next_track`
`media_player.media_pause`
`media_player.media_play`
`media_player.media_play_pause`
`media_player.media_previous_track`
`media_player.media_seek`
`media_player.media_stop`
`media_player.play_media`
`media_player.repeat_set`
`media_player.select_sound_mode`
`media_player.select_source`
`media_player.shuffle_set`
`media_player.toggle`
`media_player.turn_off`
`media_player.turn_on`
`media_player.unjoin`
`media_player.volume_down`
`media_player.volume_mute`
`media_player.volume_set`
`media_player.volume_up`

**Comment by ae8u** [comment]
> The `alexa_media` `notify` service is `notify.alexa_media` as well as ones for each of your included echo devices e.g. `notify.alexa_media_bedroom_echo_dot_left`, as well as `notify.alexa_media_last_called`.
> 
I have no notify service at all, under any name. Sent from my T-Mobile 5G Device

**Comment by danielbrunt57** [comment]
The `Dev tools` > `ACTIONS` template for `notify.alexa_media` suggests filling with this example:
```
action: notify.alexa_media
data:
  message: The garage door has been open for 10 minutes.
  title: Your Garage Door Friend
  target: platform specific
  data: platform specific
```

TTS would require it to be like this:
```
action: notify.alexa_media
data:
  message: The garage door has been open for 10 minutes.
  target: media_player.office_echo_dot_left
  data: 
    type:  tts
```
or use:
```
action: notify.alexa_media_office_echo_dot
data: 
  message: The garage door has been open for 10 minutes.
  data:
    type: tts
```

Multiple devices can be specified with the former:
```
action: notify.alexa_media
data:
  message: The garage door has been open for 10 minutes.
  target: 
    - media_player.office_echo_dot
    - media_player.kitchen_echo_dot
    - media_player.living_room_echo_dot
  data: 
    type:  tts
```
