### DISCUSSION TITLE
"Direct Music Streaming Isn't Supported" Error

### DISCUSSION THREAD

**Discussion by SMac3265** [alandtse/alexa_media_player#2774] [Q&A] [answered]
I'm almost there! I got past the "500 Internal Service" error and I have an automation set up to play a sound effect when a specific trigger is enabled. Now - my Echo Dot is complaining that "Direct Music Streaming Isn't Supported", something that is set by Amazon, and not my AMP or HA. I'm attempting to play a sound effect, about 7 sec long. My "type" is set to music. If I change the type to "sound", I do not get an error, but the sound never plays, either. In my config, I've tried just the filename.mp3, then doing local/filename.mp3, and finally, the entire path, http://192.168.50.14:8123/local/filename.mp3.  No errors, but no sound, either. I feel like I'm *THIS CLOSE* to making it work.

Oh, and if I go that URL in the browser, the sound plays fine, so that path is a good one.

Sean

**Comment by jlr2000** [comment]
I'm not sure you can play any MP3 you want, I think Amazon locks down "streaming music" (per the error you're seeing).  The only way I've been able to get this to work has been using the sounds that are available for AMP (noted in the docs).
This works for me:
```
data:
  media_content_type: sound
  media_content_id: bell_02
target:
  entity_id:
    - media_player.kitchen_show
    - media_player.tv_room
action: media_player.play_media
```
Good luck.
