### DISCUSSION TITLE
Feature to set volume level for an announcement

### DISCUSSION THREAD

**Discussion by danielbrunt57** [alandtse/alexa_media_player#2782] [Ideas]
I've worked out code to allow you to set a volume level for an announcement after which the previous volume level is automatically restored.  Here is the revised `notify.py` for you to test: [notify.zip](https://github.com/user-attachments/files/18281871/notify.zip)

To pass the temporary volume level, you code it like this:
```
action: notify.alexa_media
data:
  message: announcement
  data:
    type: announce
    volume: 0.4
  target:
    - media_player.office_echo_dot_left
    - media_player.kitchen_echo_dot
```

**Comment by popy2k14** [comment]
@danielbrunt57 first, happy new year!

Thx for your implemetation.
I have tested it. It set's the volume before sending the announcement.
This lead's to shortly jumping of the volume of the current playing media (tunein, ...).

My script from here: https://github.com/alandtse/alexa_media_player/pull/2766#issuecomment-2559356847
Is doing this some trickery to prevent this.
But it's handling all announcements synchronous when sending to more targets.

I have now made a version which respects various delays and also prevents the volume jumping of the music.
The version also is running announcements/tts in paralell (async), which is a nice addition if you have multiple echos (one i every room).
Had to change (remove) the queue delay to get precise timing.
I am not so deep in the api limitations and hope this makes no issues.
Do you know this?

Also tried it with different sentence lenght's (in german) and optimized the end delay.
Can you please test this version with multiple echo devices, like this:

```
data:
  target:
    - media_player.wohnzimmer
    - media_player.kuche
    - media_player.badezimmer
  message: "Waschmaschine ist fertig, bitte ausräumen!"
  data:
    type: announce
    volume: 0.4    
enabled: true
action: notify.alexa_media
```
Before, please manually start an tunein station with low volume like 20 (example like in the bathroom in the morning).

Download: [notify.zip](https://github.com/user-attachments/files/18286417/notify.zip)

One issue i noticed (and is currently present in my version) is: on tts the "targets" attribute does not work correctly with mutiple devices.
So just the first device in the targets list get's the tts command.
Any idea's/hint's how we can extend the tts functionality to take more target's (like announce does)?

**Reply by danielbrunt57** [reply]
> One issue i noticed (and is currently present in my version) is: on tts the "targets" attribute does not work correctly with mutiple devices.
> So just the first device in the targets list get's the tts command.
> Any idea's/hint's how we can extend the tts functionality to take more target's (like announce does)?

This is the first thing that I tested in my version and multiple targets works:
```
action: notify.alexa_media
data:
  message: this is a message
  target:
    - media_player.office_echo_dot_left
    - media_player.living_room_echo_dot_left
    - media_player.kitchen_echo_dot
  data:
    type: tts
```
I have not had a chance to look at your version yet...
