### ISSUE TITLE
Sending notifications to groups is not working. Should it?

### ISSUE THREAD

**Issue by StephanSchuster** [alandtse/alexa_media_player#1955]
**Describe the bug**

I created a media player group `media_player.alexa_all` with all my `media_player.alexa_...` via Home Assistant UI (Settings > Helpers) in order to send a notification to all of them. While it works to send notifications (announce or tts) to each individually, it does not work when I set the target to the `media_player.alexa_all` group. Am I doing something wrong or is this just not supported? Of course, I could specify a list with all my media players as target, but this is what I would like to avoid. Instead I would like to only use the group name.

**To Reproduce**

1. Create a media player group `media_player.alexa_all` via Home Assistant UI (Settings > Helpers)
2. Go to DevTools > Services and enter the following YAML:

```
service: notify.alexa_media
data:
  message: Test
  target: media_player.alexa_all
  data:
    type: announce
    method: speak
```

**Expected behavior**

All Alexa devices speak "Test".

**Observed behavior**

Nothing happens. No log errors.

**Screenshots**

![image](https://github.com/custom-components/alexa_media_player/assets/5207269/3a95c3d7-ddb5-41ec-9bbb-3708eb39fa41)

**Additional information**

Targeting individual devices works as expected with the same YAML:

```
service: notify.alexa_media
data:
  message: Test
  target: media_player.alexa_im_arbeitszimmer
  data:
    type: announce
    method: speak

```

**Comment by alandtse** [comment]
I don't think this works since the UI helper for grouping is relatively new. So happy to take a PR to add this.

**Comment by StephanSchuster** [comment]
Could this be related to https://github.com/home-assistant/core/issues/97083 ?

**Comment by Cpd5899** [comment]
> I don't think this works since the UI helper for grouping is relatively new. So happy to take a PR to add this.

Was any PR request made for this?

**Comment by Fredo70** [comment]
Notifying a group created in the Alexa app does not work either.
```yaml
    service: notify.alexa_media_uberall
    data:
      message: hallo
```
