### ISSUE TITLE
Unable to Use Piper TTS - "Sorry, I am having trouble accessing your Simon Says skill right now"

### ISSUE THREAD

**Issue by BillyFKidney** [alandtse/alexa_media_player#2091]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Attempts to use the Piper TTS service results in the Amazon Echo responding "Sorry, I am having trouble accessing your Simon Says skill right now".

I am however able to use the Nabu Casa Cloud TTS service.

**To Reproduce**

1. Configure public URL in the Alexa integration (it has a trailing / )
![image](https://github.com/custom-components/alexa_media_player/assets/65253277/9198eb43-0f98-4a0b-a7a1-b41c9175b13e)

2. Use Developer Tools to send the TTS request to use Piper
```
service: tts.speak
data:
  cache: true
  media_player_entity_id: media_player.billy_s_office_echoshow
  message: This is a test of Piper TTS
target:
  entity_id: tts.piper
```

3. Alexa responds "Sorry, I am having trouble accessing your Simon Says skill right now"

**Expected behavior**

Alexa to speak the audio created by Piper

**Screenshots**

**System details**

- Home-assistant (version):
Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

- alexa_media (version from `const.py` or HA startup):
__version__ = "4.6.5"

- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by th3Wheel** [comment]
I am getting this as well.

**Comment by sapstar** [comment]
I have setup the addon today and have exactly the same issue.

**Comment by Morpheus2018** [comment]
If I use a special character in my notify message, "&" I get an error response from Alexa "Sorry, I am having trouble accessing your Simon Says skill right now"

```
service: notify.alexa_media_alexa_echo_dot
data:
  message: test & test
  data:
    methode: all
```
