### ISSUE TITLE
Notify does not work in Kids Mode

### ISSUE THREAD

**Issue by TiPunch69** [alandtse/alexa_media_player#2156]
I do not know if this is an interface issue or an Amazon issue, but Notifications do not work on Echo devices that have "kids mode" enabled. There is no feedback, it simply will not play the notification.
"Normal" notifications via the app do work though.

I have all notifications enabled in the settings and I send the following command via the service:

````
action:
  - service: notify.alexa_media
    data:
      title: Test
      data:
        type: announce
      message: Test
      target:
        - G09XXX
 ```

If it is an Amazon limitation, maybe there is a way to give feedback, that a specific device does not support notifications in this mode, or just simply add it to the documentation, as this caused me a sleepless night to track it down :-)
