### ISSUE TITLE
Notify does not work in Kids Mode

### ISSUE THREAD

**Issue by TiPunch69** [alandtse/alexa_media_player#2157]
**Describe the bug**

No with the correct template :-)
I do not know if this is an interface issue or an Amazon issue, but Notifications do not work on Echo devices that have "kids mode" enabled. There is no feedback, it simply will not play the notification.
"Normal" notifications via the app do work though.

**To Reproduce**

1. Enable "kids mode" on an Echo device in the settings of the device
2. Send a service request for a notification
```
action:
  - service: notify.alexa_media
    data:
      title: Test
      data:
        type: announce
      message: Test
      target:
        - G09XXX
```

**Expected behavior**

If it is an Amazon limitation, maybe there is a way to give feedback, that a specific device does not support notifications in this mode, or just simply add it to the documentation, as this caused me a sleepless night to track it down

**Screenshots**

None

**System details**

- Home-assistant (version): 2023.12.3
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) yes

**Logs**

Not needed

**Additional context**
