### ISSUE TITLE
To send TTS, please set Announce=true. Music can't be played this way

### ISSUE THREAD

**Issue by Pitsaer** [alandtse/alexa_media_player#2208]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Hello I have an error for playing audio with Music Assistant to Alexa Media player.
I start playing an audio stream via Music Assistant on an Amazon device and get a error message on my Alexa device.

**To Reproduce**

1. Go to 'Music Assistant'
2. Click on 'Radio'
3. Play to 'Alexa device'
4. Hear error on Alexa device 'To send TTS, please set Announce=true. Music can't be played this way'

**Expected behavior**

I want to play radios or audio playlists via Music Assistant on my Amazon devices

**Screenshots**

No

**System details**

- Core
  2024.3.0
- Supervisor
  2024.03.0
- Operating System
  12.1.rc2
- User interface
  20240306.0

- Amazon [2FA is enabled] 
  YES
- Alexa Media Player
  v4.9.2

- Music Assistant BETA
  Current version: 2.0.0b108

**Logs**
WARNING (MainThread) [custom_components.alexa_media.media_player] To send TTS, please set Announce=true. Music can't be played this way.

This error is caused by a custom integration
Recorder: custom_components.alexa_media.media_player
Source: custom_components/alexa_media/media_player.py:1393
integration: Alexa Media Player (documentation, problems)

**Comment by Pitsaer** [comment]
For further information: https://github.com/orgs/music-assistant/discussions/431

**Comment by alandtse** [comment]
Oh wait. This is an Amazon issue.

**Comment by daknightuk** [comment]
I worked around this problem by using the alexa media player integration and using an automation to send a command to alexa.

Note that media_player.entry is the alexa where I send all my commands to just in case she ever decides to respond but the media_content_id I am specifying everything I want to do.

![image](https://github.com/user-attachments/assets/28f94813-18a3-446a-a0a4-91536e1853f5)

If I can code this so that the media content id is dynamic then I can create a dashboard with station buttons just using the voice commands.

I've used this method quite a few times particulary when I can't get devices working with home assistant but they work fine with alexa voice commands.

**Comment by PrzemekSkw** [comment]
Hello @daknightuk ,  I install Alexa-media-player integration in HA. I can play/pause and set volume but cannot play music from HA. My Alexa also tell me  the same warning about TTS. Can You explain me it's possible to fix that? Or only yay to use that integration is to make some automations like Yours for single string?
Regards

**Comment by sayam93** [comment]
> I worked around this problem by using the alexa media player integration and using an automation to send a command to alexa.
> 
> Note that media_player.entry is the alexa where I send all my commands to just in case she ever decides to respond but the media_content_id I am specifying everything I want to do.
> 
> ![image](https://private-user-images.githubusercontent.com/84586585/369602692-28f94813-18a3-446a-a0a4-91536e1853f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDY4MzIsIm5iZiI6MTczMzYwNjUzMiwicGF0aCI6Ii84NDU4NjU4NS8zNjk2MDI2OTItMjhmOTQ4MTMtMThhMy00NDZhLWEwYTQtOTE1MzZlMTg1M2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDIxMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZDM3YmQ5MDk0YzM3NDhiNDRmY2RiYmQ1N2M0NmIwMGU0ZWJjZWIzMGEyZmY3YTliOTgzOTUwMjU0OTk0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aQz24E765doAWH4SzHhM7Q8VO1617M6qmaR5GFl8etc)
> 
> If I can code this so that the media content id is dynamic then I can create a dashboard with station buttons just using the voice commands.
> 
> I've used this method quite a few times particulary when I can't get devices working with home assistant but they work fine with alexa voice commands. You just have to remember to write "how it sounds"

It's doable.

Create a script called Play Music like below:

```
alias: Play Music
sequence:
  - variables:
      music_query: "{{ music_query }}"
  - action: media_player.play_media
    metadata: {}
    data:
      media_content_id: Play "{{ music_query }}"
      media_content_type: custom
    target:
      entity_id: media_player.echo
mode: single
description: ""
```

and use an automation to feed the media_query variable like below:
```
alias: Play Music with Voice Assistant
description: ""
triggers:
  - trigger: conversation
    command:
      - Play {track} by {artist}
      - Play {track}
      - Play
    id: assistant
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - assistant
        sequence:
          - action: script.turn_on
            data:
              variables:
                music_query: |
                  {% if trigger.slots.track and trigger.slots.artist %}
                    {{ trigger.slots.track }} by {{ trigger.slots.artist }}
                  {% elif trigger.slots.track %}
                    {{ trigger.slots.track }}
                  {% else %}
                    Circles by Post Malone
                  {% endif %}
            target:
              entity_id: script.play_music
mode: single
```

The above is specific for voice commands issued to Assist in Home Assistant. You can modify the trigger so that a button press on the dashboard would provide specific data to trigger the automation. Please do share the dashboard with me if you are able to make it work. :)
