### ISSUE TITLE
Missing Echo Dot in media player

### ISSUE THREAD

**Issue by Knocks83** [alandtse/alexa_media_player#2242]
**Describe the bug**
When I go to the Media tab, if I try clicking on the available players, I cannot see the Echo Dots I have in the available devices

**To Reproduce**
1. Open the media tab
2. Click on the available devices

**Expected behavior**
My two Echo Dots should appear (I guess) in the devices list

**Screenshots**
![image](https://github.com/alandtse/alexa_media_player/assets/22529815/3c331016-7c8b-42e5-90a1-7fef1b314752)

**System details**
- Home-assistant (version): 2024.4.4
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup): apparently not installed
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Y

**Additional context**
I installed the addon using HACS and it otherwise works fine, also I tried using a script that just plays a song (which I admit I just found somewhere) and I can play music just fine: 
```yaml
data:
  entity_id: media_player.echo_dot_camera
  media_content_id: Radio Lattemiele
  media_content_type: TUNEIN
service: media_player.play_media
```
By doing that, if I also add to the dashboard my Echo Dot, I can see what I am playing just fine: 
![image](https://github.com/alandtse/alexa_media_player/assets/22529815/a9288d47-1189-4230-a617-51add9c3b4b4)

Is this actually supported? If not, is this feature even doable?
