### ISSUE TITLE
Can turn off Echo Show device screen with AMP but cannot turn it back on

### ISSUE THREAD

**Issue by dinki** [alandtse/alexa_media_player#2257]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Can turn off Echo Show device screen with AMP but cannot turn it back on

I have this as part of an automation to turn off the screen while I am sleeping:

```
service: media_player.play_media
data:
  media_content_type: custom
  media_content_id: turn off display
target:
  entity_id:
    - media_player.donny_s_echo_show_5_2nd_gen
```

but this service call does not turn the screen back on though issuing the same command with voice does:

```
service: media_player.play_media
data:
  media_content_type: custom
  media_content_id: show clock
target:
  entity_id: media_player.donny_s_echo_show_5_2nd_gen
```

Perhaps there is another way to do this but I would like to be able to automate the ability to turn the screen on and off.

Thanks!

**System details**

- Home-assistant (version):   2024.5.2
- alexa_media (version from `const.py` or HA startup): 4.10.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :  yes
