### ISSUE TITLE
Sound effects not playing

### ISSUE THREAD

**Issue by bturrie** [alandtse/alexa_media_player#2291]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

I cannot play amazon sound effects in scripts or automations. The logs show nothing

to reprodruce create a script similar to:

  main_ac_fail:
    alias: 'main_ac_fail'
    sequence:
      - service: media_player.volume_set
        target:
          entity_id: media_player.great_room
        data:
          volume_level: 0.7
      - service: media_player.play_media
        target:
          entity_id: media_player.great_room
        data:
          media_content_type: sound
          media_content_id:  "amzn_sfx_scifi_alarm_04"
      - service: media_player.volume_set
        target:
          entity_id: media_player.great_room
        data:
          volume_level: 0.4

1. Go to 'Developer tools
2. Scroll down to 'main_ac-fail.yaml'
3. select 'main_ac-fail.yaml' and press Run
4. Nothing is in the logs

**Expected behavior**
I would expect to hear a beep then the sound effect after a short delay and then a quiter beep

**Screenshots**

**System details**

- Home-assistant (version): 2024.6.3
- alexa_media (version from `const.py` or HA startup): 4.10.2
- alexapy (version from `pip show alexapy` or HA startup):  1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).  Yes:

**Logs**
Nothing related to alexa media appears in the logs even with debugging enabled
**Additional context**

**Comment by bturrie** [comment]
Not sure why the indentations disappeared in my code ir ther right way to have entered them. That said that said code that used to work no longer does on my HA system

**Comment by danielbrunt57** [comment]
Select your code and use the code wrapper button `<>` to encase your code with triple back quotes!
![image](https://github.com/alandtse/alexa_media_player/assets/49846893/3cac33b4-9594-4ab8-8e64-6988578c4b35)

```
alias: main_ac_fail
sequence:
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      entity_id: media_player.office_echo_dot_left
  - service: media_player.play_media
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_scifi_alarm_04
    target:
      entity_id: media_player.office_echo_dot_left
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id: media_player.office_echo_dot_left
```
