### ISSUE TITLE
Integration stop working after some time: `Login error detected; not contacting API`

### ISSUE THREAD

**Issue by antoweb** [alandtse/alexa_media_player#2448]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

WHen i use media_player alexa wont work, the integration must be reloaded for retunr to working

**To Reproduce**

1. Run an action for alexa media player (tts)
2. Alexa wont talk

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2024.8.0
- alexa_media (version from `const.py` or HA startup):4.12.7
- alexapy (version from `pip show alexapy` or HA startup):4.12.7
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**

Logs

2024-08-09 15:18:43.563 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 960, in send_announcement
await self.send_sequence(
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
await self.run_behavior(node_data, queue_delay=queue_delay)
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
await self._post_request("/api/behaviors/preview", data=data)
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
return await self._request("post", uri, data, query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
ret = await target(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API
2024-08-09 15:18:55.761 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 960, in send_announcement
await self.send_sequence(
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
await self.run_behavior(node_data, queue_delay=queue_delay)
File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
await self._post_request("/api/behaviors/preview", data=data)
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
return await self._request("post", uri, data, query)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
ret = await target(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API
2024-08-09 15:18:59.798 ERROR (MainThread) 
Additional context

**Comment by antoweb** [comment]
same issue as https://github.com/alandtse/alexa_media_player/issues/2442

**Comment by ob1w4nken0b1** [comment]
+1 on this

**Comment by rymiller11** [comment]
+1 on this

**Comment by javilopezalarcon** [comment]
+1

**Comment by jleinenbach** [comment]
As I don't have this issue: Have you already tried to:
- remove the integration
- delete the config/.storage/alexa_media.[email-address].pickle file
- install and configure the integration again?

**Comment by antoweb** [comment]
> As I don't have this issue: Have you already tried to:
> 
> * remove the integration
> * delete the config/.storage/alexa_media.[email-address].pickle file
> * install and configure the integration again?

Yes nothing changed

**Comment by chrisvblemos** [comment]
@antoweb , few questions...

Domain?
Using 2FA with external authenticator app?
Using external Home Assistant URL?
Can you check logs for any HTTP2 mentions related to AMP?

**Comment by antoweb** [comment]
Issue Is common in Europe see other issue already opened mentioned above
Anyways:
2fa with permanente token
External url public
Log are above

**Comment by jleinenbach** [comment]
I'm in Europe (amazon.de) and don't have these issues.
> alexapy (version from pip show alexapy or HA startup):4.12.7
This should should be v1.28.2

Your logs do not include the issue, the errors are just a result of it.
You should reboot, activate the debuglogs, reload the integration, wait until it fails, then save the logs.

**Comment by javilopezalarcon** [comment]
I'm amazon.es and i have these problems

**Comment by gutisoft2** [comment]
Yo soy Amazon.es y también tengo ese problema. Las automatizaciones funcionan perfectamente, pero no anuncia nada Alexa.
Probe en desinstalar Alexa media, reiniciar, elimiar el archivo del config y nada de nada.
De momento la única solución temporal, reiniciar Alexa cada 10 minutos.

**Comment by zibous** [comment]
> I'm in Europe (amazon.de) and don't have these issues.

Same here:

AlexaPy Version: 1.28.2
alexa_media: "4.12.7"
homeassistant: 2024.8.1 Dockerversion

1. Reinstall alexa_media player 
2. Register ad amazon.de all devices work perfectly 
3. --> No Error ! 
4. restart Homeassistant 
5. --> Error http.cookies.CookieError: Invalid attribute 'partitioned'


```log
2024-08-11 07:21:44.774 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *****@***.com - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 359, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```

Current workaround:

```yaml
- id: reload_alexa_on_start
      alias: Reload Alexa Media Player after HA starts
      description: "Behebt den Fehler, damit alle Alexa Media Player nach dem Start wiedelr laufen...."
      initial_state: true
      trigger:
        - platform: homeassistant
          event: start
      condition: []
      action:
        - delay:
            hours: 0
            minutes: 1
            seconds: 0
            milliseconds: 0
        - alias: Reload Alexa Media Player integration
          service: homeassistant.reload_config_entry
          data: {}
          target:
            entity_id:
              - "media_player.alexa1" #single echo device
              - "media_player.alexa2" #single echo device
              - "media_player.alexa3" #single echo device
              - "media_player.alexa4" #single echo device
              - "media_player.alexa5" #single echo device
              - "media_player.alexa6" #single echo device
```

sorry, stressful and it's a shame that it doesn't work anymore.
