### ISSUE TITLE
Error fetching alexa_media data: Error communicating with API: Too Many Requests - all devices disappear

### ISSUE THREAD

**Issue by samuele2723** [alandtse/alexa_media_player#2558]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I am using this integration since few years, i was using it without any issue since a month ago, while upgrading to 4.13+ i had authentication issue, so i went back to 4.12.

Then, the 12th of september after a HA restart, all alexa echo devices appear offline ever since. I tried to reinstall the intregration, upgrade and reauthenticate from fresh, but in case of a fresh new installation the list doesn't appear at all (therefore why is unavailable in the list already present since previous)

**To Reproduce**

i can install a fresh new integration and list of devices not appearing even if the alexa account is active and devices there and working 

ì

**System details**

- Home Assistant version: 2024.6.3 but i also tried 2024.9.2
- alexa_media version (from `const.py` or HA startup log):
<img width="1541" alt="Screenshot 2024-09-22 alle 22 14 19" src="https://github.com/user-attachments/assets/5dc61e77-1f76-40ba-954e-1b2a86c1af0c">

- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): YES
- Amazon Domain: amazon.it

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
<img width="1551" alt="Screenshot 2024-09-22 alle 22 14 54" src="https://github.com/user-attachments/assets/5e2de1f1-4ec7-47bf-8cd7-e61e5527e7b8">

**Additional context**

**Comment by bennydente** [comment]
Same here. on home assistant core 2024.9.2 and alexa media player 4.13.2.

thanks, bye

**Comment by c2mfj** [comment]
adding another one
`2024-09-23 13:14:15.725 WARNING (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f30da34bdd0>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
('can only concatenate str (not "NoneType") to str',)
2024-09-23 13:14:15.725 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <myEmailAddress> - amazon.com for alexa_media`

**Comment by kyleb822** [comment]
Same here, integration is now saying “Failed setup, will retry: Connection Error during login”

HA 2024.9.2
AMP 4.13.2

**Comment by 38Cherry** [comment]
same.
![image](https://github.com/user-attachments/assets/bbcbb8b6-6bc4-438b-ab3f-2928ccb28954)
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 11:59:31 AM (1 occurrences)
Last logged: 11:59:31 AM

Error setting up entry xxx@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to st

and 

This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/__init__.py:361
integration: Alexa Media Player (documentation, issues)
First occurred: 11:59:31 AM (1 occurrences)
Last logged: 11:59:31 AM

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7fbe9f8be120>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('can only concatenate str (not "NoneType") to str',)

**Comment by dersch81** [comment]
Same here 

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: alexapy.helpers
Quelle: custom_components/alexa_media/__init__.py:361
Integration: Alexa Media Player (Dokumentation, Probleme)
Erstmals aufgetreten: 23:34:56 (3 Vorkommnisse)
Zuletzt protokolliert: 23:41:56

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7fcd9dd922d0>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('can only concatenate str (not "NoneType") to str',)
```

AMP 4.13.2
HASS 2024.9.2

**Comment by stefanomarino75** [comment]
Same problem Too Many Requests

**Comment by ruralleafowner** [comment]
Same issue. Have spent hours on it, as do NOT want to delete and reinstall, worried it will get rid of all the automations I have setup.

Is it possible to re-authenticate the media player as I think this may be the issue? (I do not get the option to do this sadly!)

**Comment by darioz90** [comment]
Same issue after 20/30 min -> “All devices unavailable”

i try time polling to 500 , but don’t work

HA core 2024.9.2
AMP 4.13.2

**Comment by mifraburneo** [comment]
Exact same issue.
HA core 2024.9.2
AMP 4.13.2

Poorly tried changing public domain to local ip and adding and removing trailing /
Also to reinstall the integration
Nothing so far...

**Comment by delboydell** [comment]
Same here for me in the UK
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 08:51:19 (1 occurrences)
Last logged: 08:51:19

Error setting up entry p.p.*******@*******net.com - amazon.co.uk for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 671, in login
    site = await self._process_page(html, site)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
	
	
	
	
	
	This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/__init__.py:361
integration: Alexa Media Player (documentation, issues)
First occurred: 08:51:19 (1 occurrences)
Last logged: 08:51:19

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7fe1963f2150>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('can only concatenate str (not "NoneType")

**Comment by 121Westlife212** [comment]
Same here for me (Spain)
Registrador: homeassistant.config_entries
Fuente: config_entries.py:604
Ocurrió por primera vez: 07:48:50 (1 ocurrencias)
Última vez registrado: 07:48:50

Error setting up entry jo****e*********@*******.com - amazon.es for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

**Comment by cagnulein** [comment]
Same issue unfortunately :(

**Comment by c2mfj** [comment]
I got mine working by updating to HA Core 2024.9.3. (that seemed to remove the "none type" error I was getting before) but then I was getting a generic authentication failure error in the logs. 

I removed the AMP integration, restarted Home Assistant, and re-added it. Ran through the setup and everything is working again. For those who said they are worried about automations, the devices picked right back up and I didn't miss a beat.

**Comment by PV-Joe** [comment]
Same problem here in Germany.
Please fix.

**Comment by bennydente** [comment]
Hi, there is a workaround for endless loop signin here. https://github.com/alandtse/alexa_media_player/issues/2514
In my scenario, after uninstall and reinstall, the integration stop working after some minutes and I receive this error
""" An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)""""

**Comment by PV-Joe** [comment]
I did use that workaround. After the next restart AMP was disconnected again.

Accidentally logging into amazon.com instead of amazon.de didn't have any issue.

This is really annoying.
Hope for a fix.

**Comment by zav13r** [comment]
I think linked to this issue, after removing and reinstalling integration and following the workaround for the login loop, I receive a blank 'Error' dialogue back in HA at the final step and nothing is added.

This is using 2SV and both amazon.com and amazon.co.uk domains in setup.

**Comment by CommittotheIndian** [comment]
I'm in the same boat. I've tried removing the component completely, reinstalling, and now I get an error when trying to log in. I've gone back all the way to v12.2

**Comment by mattia93cz** [comment]
using AMP version 4.12.7 and 2024.9.3 for HA I don't encounter any problems. 
To resolve the authentication loop:
instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned.
Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.

**Comment by CommittotheIndian** [comment]
> using AMP version 4.12.7 and 2024.9.3 for HA I don't encounter any problems. To resolve the authentication loop: instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned. Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.

I've done this multiple times. Its when I get returned to HA that HA just shows a blank error screen.

**Comment by zav13r** [comment]
> > using AMP version 4.12.7 and 2024.9.3 for HA I don't encounter any problems. To resolve the authentication loop: instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned. Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.
> 
> I've done this multiple times. Its when I get returned to HA that HA just shows a blank error screen.

This ^

It is not the Amazon login or 2SV that's the issue. The workaround for create new, then login works. It's back in HA at the final step that the error is generated and setup of thr integration fails.

**Comment by mattia93cz** [comment]
> > > using AMP version 4.12.7 and 2024.9.3 for HA I don't encounter any problems. To resolve the authentication loop: instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned. Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.
> > 
> > 
> > I've done this multiple times. Its when I get returned to HA that HA just shows a blank error screen.
> 
> This ^
> 
> It is not the Amazon login or 2SV that's the issue. The workaround for create new, then login works. It's back in HA at the final step that the error is generated and setup of thr integration fails.

By following this procedure I was able to get the installation to work several times.
Using chrome and trying to create a new account before logging in has always worked for me.
Importantly, you do not need to refresh the web page

**Comment by zav13r** [comment]
I don't know what to tell you - it's great that it works for you, I'm simply saying that it doesn't for me, and others.

- New chrome browser install, logged into amazon
- 2SV setup correctly
- Create new account on Amazon login page, then 'user already registered' to login
- HA recognises this, begins final setup and returns a blank Error box
- Integration is not loaded.

- Tried uninstalling AMP, deleting pickle file, restart and re download. No joy

This is on the latest AMP version, and up to date HA install.

**Comment by CommittotheIndian** [comment]
> > > > using AMP version 4.12.7 and 2024.9.3 for HA I don't encounter any problems. To resolve the authentication loop: instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned. Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.
> > > 
> > > 
> > > I've done this multiple times. Its when I get returned to HA that HA just shows a blank error screen.
> > 
> > 
> > This ^
> > It is not the Amazon login or 2SV that's the issue. The workaround for create new, then login works. It's back in HA at the final step that the error is generated and setup of thr integration fails.
> 
> By following this procedure I was able to get the installation to work several times. Using chrome and trying to create a new account before logging in has always worked for me. Importantly, you do not need to refresh the web page

This was even after completely removing AMP, removing config files, clearing cookies, removing alexa and .pickle within .storage.

I reinstalled at AMP 4.12.11 and on HA 2024.8.2.

As you can see the Amazon login/workaround for creating an account works. It's when we get back to HA, we get the error.

![image](https://github.com/user-attachments/assets/5be4b60c-1a32-4172-9cbf-b757579bc035)

**Comment by Toxo666** [comment]
Maybe this helps?

https://github.com/alandtse/alexa_media_player/issues/2554#issuecomment-2381869404

**Comment by zav13r** [comment]
> Maybe this helps?
> 
> https://github.com/alandtse/alexa_media_player/issues/2554#issuecomment-2381869404

Oh, thank you!! This was it for me, using pi hole. Disabling blocking didn't seem to work but adding the new regex fixed it. AMP seems to be working again.

**Comment by bennydente** [comment]
Thanks, but trying adding whitelist regex filter or disabling blocking for exact domain not working for me. I have same error after some minutes.

" An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)"

**Comment by Eric-boop** [comment]
I found the answer on github!: "Are any of you using an ad blocker/firewall such as Pi-hole or AdGuard by chance? Some adlists were recently updated to block the Amazon Alexa API. This is solved by adding ^api(\.[a-z]+)?\.amazonalexa\.com$ to your Pi-hole whitelist or @@||api*.amazonalexa.com^ for AdGuard. This regex is not region specific and should work for all endpoints"

**Comment by chesterflaps** [comment]
Same issue for me. Suddenly all alexa devices are showing as unavailable.

**Comment by danielbrunt57** [comment]
> I found the answer on github!: "Are any of you using an ad blocker/firewall such as Pi-hole or AdGuard by chance? Some adlists were recently updated to block the Amazon Alexa API. This is solved by adding ^api(.[a-z]+)?.amazonalexa.com$ to your Pi-hole whitelist or @@||api*.amazonalexa.com^ for AdGuard. This regex is not region specific and should work for all endpoints"

This might very well be the cause of the myriad of issues other users have had that I have not.   I've never used an ad blocker and my firewall is CloudFlare where I allow Amazon domain unrestricted access...

**Comment by danielbrunt57** [comment]
> However, with amazon.com, I am unable to control any devices, though all of my devices are available when using amazon.com. If I try with amazon.de, no devices are shown.

If your devices are registered via your account at amazon.com then you need to use amazon.com.

![image](https://github.com/user-attachments/assets/7ecab2c7-52de-4e84-b562-b880021522b8)

If your devices are registered via your account at amazon.de then you need to use amazon.de.

![image](https://github.com/user-attachments/assets/9cbb164a-0e45-463b-a747-cd590584ee93)

**Comment by danielbrunt57** [comment]
> with amazon.com, I am unable to control any devices

@elbrondor What devices are you trying to **_control_**?
AMP does not **_control_** any devices, only `notify.alexa_media` and `media_player._xyz_` commands...

**Comment by itzalgd24** [comment]
I can confirm that whitelisting ^api(.[a-z]+)?.amazonalexa.com$ in Pi-Hole fixed the issue for me.

**Comment by elbrondor** [comment]
Hello All,
i like to control my Amazon Echo devicves. All of them are registerd to Amazon.de
![grafik](https://github.com/user-attachments/assets/c397c134-0e86-4513-9275-0ddc8cfeeffc)
but in Home assistant AMP is see:
![grafik](https://github.com/user-attachments/assets/cf5e405b-c6e1-4a8a-86de-b54b1c30dc2a)

**Comment by elbrondor** [comment]
Here are the related log lines:

2024-10-04 15:22:38.796 DEBUG (MainThread) [custom_components.alexa_media] Discovered new media_player G************09G
2024-10-04 15:22:38.922 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/phoenix returned 429:Too Many Requests:application/json
2024-10-04 15:22:38.923 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 0.6s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-10-04 15:22:38.958 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/bootstrap returned 200:OK:application/json
2024-10-04 15:22:39.023 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/devices-v2/device returned 200:OK:application/json
2024-10-04 15:22:39.033 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/dnd/device-status-list returned 200:OK:application/json
2024-10-04 15:22:39.196 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/bluetooth?cached=false returned 200:OK:application/json
2024-10-04 15:22:39.423 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/device-preferences returned 200:OK:application/json
2024-10-04 15:22:39.591 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/phoenix returned 429:Too Many Requests:application/json
2024-10-04 15:22:39.592 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 1.5s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-10-04 15:22:41.191 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/phoenix returned 429:Too Many Requests:application/json
2024-10-04 15:22:41.191 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 3.9s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-10-04 15:22:45.127 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/phoenix returned 429:Too Many Requests:application/json
2024-10-04 15:22:45.128 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 3.9s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-10-04 15:22:49.120 DEBUG (MainThread) [alexapy.alexaapi] J*****************r@g****e: static GET: https://alexa.amazon.de/api/phoenix returned 429:Too Many Requests:application/json
2024-10-04 15:22:49.120 ERROR (MainThread) [alexapy.alexaapi] Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-10-04 15:22:49.120 WARNING (MainThread) [alexapy.helpers] alexaapi.get_guard_details((<alexapy.alexalogin.AlexaLogin object at 0x7f550664b4d0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
('Too Many Requests',)
2024-10-04 15:22:49.121 WARNING (MainThread) [alexapy.helpers] alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f550664b4d0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
('Too Many Requests',)
2024-10-04 15:22:49.122 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 10.336 seconds (success: False)

**Comment by oentzforeva** [comment]
None of the solutions are working for me anymore. Amazon login loop, workaround - check. Reconfiguration to my domain .de - check. Pihole regex whitelist for api.amazonalexa.* - check. No changes. All the entities are in a "not available" state. I tried several versions of HA Core and AMP. I cant get it to work at all. After every reconfiguration alexa app is saying that it detected some new devices, but its not possible to control anything from HA. Any solution would be great. I could provide logs, but nothing which wasn't already posted here.

**Comment by samuele2723** [comment]
> Hello All, i like to control my Amazon Echo devicves. All of them are registerd to Amazon.de ![grafik](https://private-user-images.githubusercontent.com/89851839/373170817-c397c134-0e86-4513-9275-0ddc8cfeeffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Mzk2MjgsIm5iZiI6MTcyODkzOTMyOCwicGF0aCI6Ii84OTg1MTgzOS8zNzMxNzA4MTctYzM5N2MxMzQtMGU4Ni00NTEzLTkyNzUtMGRkYzhjZmVlZmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDIwNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OTU1YzAyYzA1ZWMxZGJhMWJmOTcxN2NlMmQ4MDNmM2FjODVhM2MxYTRiOWZjMTJhZmUwNjczN2Q3MDg0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yQ4X-hqFRFebr6MByfP2QcxDzakGYzFNkMljVDaJBGw) but in Home assistant AMP is see: ![grafik](https://private-user-images.githubusercontent.com/89851839/373171337-cf5e405b-c6e1-4a8a-86de-b54b1c30dc2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Mzk2MjgsIm5iZiI6MTcyODkzOTMyOCwicGF0aCI6Ii84OTg1MTgzOS8zNzMxNzEzMzctY2Y1ZTQwNWItYzZlMS00YThhLTg2ZGUtYjU0YjFjMzBkYzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDIwNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNWNiZmZhNWJmMzI5Y2FhYWVlZGQ1MGIyOTgwMmMyMjczNWUyMTgxZTU3NjBhMTNlY2M0NGEzYWVlMzI3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OWRXRVP8M4ml-TdORu9r3LaIOlNsdxPx7MEy45ueko4)

Same situation, i managed to get out of the infinite loop and integration is logged in but sees no devices

<img width="749" alt="image" src="https://github.com/user-attachments/assets/abd05358-a2ea-44c8-8a3f-4f9596e5916b">

still i have device in account
<img width="640" alt="Screenshot 2024-10-14 alle 22 57 03" src="https://github.com/user-attachments/assets/b29a0af6-140b-4618-b602-fac12336fa35">

please any can support or share workarounds? here logs i have from HA register
<img width="1509" alt="Screenshot 2024-10-14 alle 22 57 33" src="https://github.com/user-attachments/assets/df9dfc5a-4dc2-47eb-ac68-bda2ce84095c">

**Comment by ah92uk** [comment]
After suffering the same issue and spending countless hours back and to with Amazon support (online, phone and email) my solution has been to create a new Amazon account specifically for Alexa devices and use this.

So far, after around a week, it's working fine still - my secondsbetweenscans = 60s and I've only added the few Echos I have and around a dozen Home Assistant switches exposed via Home Assistant rather than the many dozens of devices I had previously.

I'm hoping by scaling down to neccessary devices only I'll reduce API calls and hopefully not get seemingly shadowbanned again.

FWIW also, when I logged into the Alexa app for the first time with my new account it looked like an updated GUI despite being the same app version I was logged into previously - I don't know if maybe older Amazon accounts are getting stuck in a sort of API limbo?

**Comment by Pirol62** [comment]
Maybe, that is a good point to find a solution. From the beginning, I only exposed entities, I really need. All domains are forbidden and the entities I need are listed explicitly. That maybe avoids to much unnecessary traffic. Even I stay at 2024.8.3 I never faced any issues

**Comment by danielbrunt57** [comment]
> my solution has been to create a new Amazon account specifically for Alexa devices and use this.

Does this require a different email address?

**Comment by danielbrunt57** [comment]
> From the beginning, I only exposed entities, I really need.

Are you referring to HA entities exposed to the Alexa Smarthome Skill?

I really only need AMP to be able to `notify.alexa_media_last_called` and I only have one instance where I use `notify.alexa_media_some_echo_device`.  I don't even use the media_player.play_media/media_play functionality.

The code in alexapy is very out-of-date comapred to the coding I'm seeing in [](https://www.npmjs.com/package/alexa-remote2?activeTab=code), which AMP was originally derived from, way back when.

**Comment by Pirol62** [comment]
I'm referring HA entities, that I expose via yaml config to AMP
````
alexa:
  filter:
    exclude_domains:
      - light
      - button
      - automation
      - sensor
      - binary_sensor
      - media_player
      - group
      - cover
      - remote
      - climate
      - script
      - scene
      - input_boolean
      - input_number
      - timer
      - camera
      - switch
      - number
    include_entities:
      - button.x3_xdrive30d_klimaanlage_aktivieren
      - input_boolean.yvonne_stays_at_home
      - input_boolean.evening_scene_active
      - input_boolean.holiday_mode
      - input_boolean.reading_light
      - input_boolean.guest_mode
      - light.kuche
      - light.fenster_kueche
      - light.haustuer
      - light.flur
      - light.fitnessraum
      - light.treppe
      - light.schlafzimmer
      - light.office
      - light.gastezimmer
      - light.wohnzimmer
      - light.wohnzimmer_spot1
      - light.wohnzimmer_spot2
      - light.wohnzimmer_esstisch_unten
      - light.wohnzimmer_esstisch_oben
      - light.gartenleuchten
      - script.command_alarm
      - script.command_alarm_off
      - script.command_start_yvonnes_desktop
      - script.command_stop_yvonnes_desktop
      - script.command_humidifier_on
      - script.command_humidifier_off
      - script.command_bright_light
      - script.command_climate_off
      - script.command_climate_lower
      - script.command_climate_higher
      - script.command_boost_air_condition
      - script.command_dim_light
      - script.command_halogen_light
      - script.command_tv_light
      - script.command_night_light
      - script.command_light_on
      - script.command_light_off
      - script.command_all_lights_off
      - script.command_light_volumedown
      - script.command_light_volumeup
      - script.command_light_garden_volumedown
      - script.command_light_garden_volumeup
      - script.command_light_esstisch_volumedown
      - script.command_light_esstisch_volumeup
      - script.command_light_permanent_off
      - script.command_light_permanent_on
      - script.command_light_45_off
      - script.command_sleepmode
      - script.command_sleepmode_off
      - script.command_activate_light
      - script.command_deactivate_light
      - script.command_fernsehlicht_on
      - script.command_krimi_on
      - script.command_esstisch_on
      - script.command_fussball_on
      - script.command_party_on
      - script.command_weihnachten_on
      - script.command_essen_on
      - script.command_volume_up
      - script.command_volume_down
      - script.command_slight_volume_up
      - script.command_slight_volume_down
      - script.command_big_volume_up
      - script.command_big_volume_down
      - script.command_szene_good_night
      - script.command_last_active_scene_on
      - script.command_play_music
      - script.command_play_meerbar
      - script.command_play_chillout2023
      - script.command_play_absolute_chillout
      - script.command_play_jazz
      - script.command_play_piano
      - script.command_pause
      - script.command_play
      - script.command_cover_down
      - script.command_cover_up
      - script.command_set_delay_reminder
      - script.activate_cameras
      - script.command_training_session
      - script.deactivate_cameras
      - script.question_outside_temperature
      - script.question_inside_temperature
      - script.question_how_long_washing
      - script.question_where_is_joerg
      - script.question_next_reminder
      - script.question_hows_my_way_to_work
      - script.question_last_alexa_message
      - script.command_play_antenne_bayern
      - script.command_play_absolute_chillout
      - script.command_play_wdr2
      - script.command_play_1live
      - script.command_play_charivari
      - script.command_play_aladin
      - script.command_play_trance
      - script.command_play_christmas
      - script.command_play_raggae
      - script.command_play_party
      - script.command_stop_music
      - script.command_stop_harmony
      - script.command_climate_lower
      - script.command_climate_higher
      - script.command_diffusor_off
      - script.command_diffusor_on
      - switch.mute_on_off
      - switch.pc_yvonne
      - switch.ventilator
    ````
