### ISSUE TITLE
custom Alexa command 

### ISSUE THREAD

**Issue by mikeaumiller** [alandtse/alexa_media_player#2630]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Possibly? Send a custom Alexa command that has the value of a sensor

**Describe the solution you'd like**
Within the media_content_id field I would like to use the value of a sensor as part of the command within media_player.play_media Action. Before sending the command the sensor value would be translated.

**Describe alternatives you've considered**
None

**Additional context**
Example: Alexa, move music to <sensor.room_name> echo’ would result in sending: Alexa, move music to family room echo

**Comment by danielbrunt57** [comment]
I just tried this and it worked fine:
```
action: media_player.play_media
data: 
  media_content_type: custom
  media_content_id: "move music to {{ state_attr('sensor.last_alexa', 'actual_friendly_name') }}"
target:
  entity_id: media_player.kitchen_echo_dot
```
My sensor.last_alexa is highly customized but you should be able to template your <sensor.room_name>...

![image](https://github.com/user-attachments/assets/8f6b9625-bcf9-43e0-a848-45fc4e1a5e5a)

**Comment by danielbrunt57** [comment]
Your automation action is missing a target `entity_id:`
```
  - action: media_player.play_media
    metadata: {}
    data:
      media_content_type: custom
      media_content_id: move music to {{ states('sensor.galaxy_s24_ultra_ble') }} echo
```

![image](https://github.com/user-attachments/assets/00bc1761-15d9-4c3c-8928-6cec4135d3c7)
