### ISSUE TITLE
Change and restore volume for announcements

### ISSUE THREAD

**Issue by StefanW86** [alandtse/alexa_media_player#2735]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I often use my echos for TTS announcements, e.g. the doorbell rang, washing machine ready.
However, my echos are often set to volume 1.

It would therefore be great if there was a parameter that could be added to a TTS announcement that raises the volume to a defined value, executes the TTS announcement and then resets the volume to the old value.

With Sonos integration, this is possible via the “announce” parameter.

**Describe alternatives you've considered**
i dont know any alternative

**Additional context**
-

**Comment by sayam93** [comment]
> **NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**
> 
> **Is your feature request related to a problem? Please describe.** no
> 
> **Describe the solution you'd like** I often use my echos for TTS announcements, e.g. the doorbell rang, washing machine ready. However, my echos are often set to volume 1.
> 
> It would therefore be great if there was a parameter that could be added to a TTS announcement that raises the volume to a defined value, executes the TTS announcement and then resets the volume to the old value.
> 
> With Sonos integration, this is possible via the “announce” parameter.
> 
> **Describe alternatives you've considered** i dont know any alternative
> 
> ## **Additional context**

This can be done within the automation itself. 

You can add something like the below both before and after the tts announce action:

```
action: media_player.volume_set
metadata: {}
data:
  volume_level: 0.7
target:
  entity_id: media_player.echo
```

Let me know if it works.

**Comment by StefanW86** [comment]
I'm not quite sure if I've understood you correctly. 
With your snippet I change the volume.

My problem is that I don't know what the current volume is to go back to it after the tts.

Example:
Music is playing at volume 1. Now I set the volume to 3 as you described, play the TTS and set it back to 1. 
That would work.

However, if the music is now playing at level 3, I would set it back to 1 after the TTS and it would be too quiet.

It would therefore be great if there was an announce feature that remembers the original volume, plays TTS or other at the desired volume and then jumps back to the original volume.

**Comment by sayam93** [comment]
> I'm not quite sure if I've understood you correctly. With your snippet I change the volume.
> 
> My problem is that I don't know what the current volume is to go back to it after the tts.
> 
> Example: Music is playing at volume 1. Now I set the volume to 3 as you described, play the TTS and set it back to 1. That would work.
> 
> However, if the music is now playing at level 3, I would set it back to 1 after the TTS and it would be too quiet.
> 
> It would therefore be great if there was an announce feature that remembers the original volume, plays TTS or other at the desired volume and then jumps back to the original volume.

For this, you could refer to https://community.home-assistant.io/t/turn-back-previous-volume-state-of-media-player/233396/9

**Comment by StefanW86** [comment]
Great, that works.
It's a bit more work in automation, but it's a solution.

So do you think the feature request is unnecessary? The Sonos integration offers such a parameter and does the work.

**Comment by sayam93** [comment]
> Great, that works. It's a bit more work in automation, but it's a solution.
> 
> So do you think the feature request is unnecessary? The Sonos integration offers such a parameter and does the work.

The feature request is definitely a good idea. This is just a stopgap solution.

**Comment by StefanW86** [comment]
I'm glad to hear that. Many thanks for the quick help

**Comment by danielbrunt57** [comment]
And who do you think is going to pick up that coding endeavor? Certainly not the developer Alan Tse. He ceased developing more than a year ago, maybe even 2 or 3. That only leaves contributors and I for one am not going to tackle it...

**Comment by danielbrunt57** [comment]
That is the easiest for everyone to use.  And if you need to determine how long the announcement is going to take before you restore the volume level, you can calculate a delay based on the word count in the message.  I use this technique in my central `Alexa: Notify Alexa Media Last Called` script:
```
alias: "Alexa: Notify Alexa Media Last Called"
description: Send notification to sensor.last_alexa
fields:
  message:
    description: The message content
    example: I am notifying you
sequence:
  - action: python_script.notify_alexa_media_last_called
    data:
      message: "{{ message }}"
  - delay:
      seconds: >-
        {{ (message.split(' ') | count *
        states('input_number.alexa_word_duration')|float ) | round(0, 'floor',
        default) }}
    alias: Delay for word count * 0.55s
  - if:
      - condition: template
        value_template: "{{ states('sensor.last_alexa') != 'unknown'}}"
        enabled: false
      - condition: state
        entity_id: input_boolean.alexa_media_notify_service_registered
        state: "on"
        enabled: true
    then:
      - action: notify.alexa_media_last_called
        data:
          message: "{{ message }}"
        enabled: true
    enabled: false
  - action: notify.alexa_media_last_called
    data:
      message: "{{ message }}"
    enabled: false
mode: queued
icon: mdi:account-voice
max: 10
```
