### ISSUE TITLE
Notify.alexa_media does not work with groups (or any non alexa_media entities).

### ISSUE THREAD

**Issue by fabio-s-franco** [alandtse/alexa_media_player#2801]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.** ✅

According to [the wiki on tts](https://github.com/alandtse/alexa_media_player/wiki/Configuration%3A-Notification-Component#tts), I should be able to target rooms, serialnumbers (for echo device for example) and other groupings, but it does not seem to work, except if the target is the alexa_media entity itself.

I crated a script to facilitate TTS action via a button in the dashboard and this is how it looks:

```yaml
sequence:
  - action: notify.alexa_media
    data_template:
      title: Alexa Speak...
      data:
        type: tts
      message: "{{message}}"
      target: |
        [
          {%- for key, values in targets.items() -%}
            {%- if values is string -%}
              "{{ values }}"
            {%- else -%}
              {%- for value in values -%}
                "{{ value }}"{% if not loop.last %}, {% endif %}
              {%- endfor -%}
            {%- endif %}
          {%- if not loop.last %}, {% endif %}
          {%- endfor -%}
        ]
alias: Echo talk
description: ""
fields:
  message:
    selector:
      text: null
    name: Message
    required: true
  targets:
    selector:
      target:
        entity:
          domain: media_player
          integration: alexa_media
    name: Targets
    description: Select Amazon Echo devices or areas to send your message to
    required: true
    default:
      entity_id: media_player.echo_main
mode: queued
max: 15
```

It was already tricky to get this to work at all, because the direct output of a target selector has an extra level in the result. Example:

![Image](https://github.com/user-attachments/assets/24c300d1-3826-489a-948b-462acf5db33c)

```yaml
params:
  domain: notify
  service: alexa_media
  service_data:
    title: Alexa Speak...
    data:
      type: tts
    message: test
    target:
      area_id: office
  target: {}
```

Ended up with that ugly templating, difficult to figure out, because the result of the selector has a different type if it is a single item (string), or multiple (dictionary).
Having the right template in place, I was able to have it output the way the integration expects it (or at least matches the format in the example):

```yaml
params:
  domain: notify
  service: alexa_media
  service_data:
    title: Alexa Speak...
    data:
      type: tts
    message: test
    target:
      - office
```

But that doesn't work. My assumption is that it would do an expansion, similar to what the UI does.
If I do expand in the UI (have to expand twice, as the echo device directly also doesn't work. room -> device -> entity), then it works:

![Image](https://github.com/user-attachments/assets/c4e23d5c-2703-448c-903f-8244e0041203)

```yaml 
params:
  domain: notify
  service: alexa_media
  service_data:
    title: Alexa Speak...
    data:
      type: tts
    message: test
    target:
      - media_player.echo_office_1
      - media_player.office
```

Is there something I am missing here? 

Either way, thanks for the fine work on this integration. Have been looking into this a long time for a project, integrating directly to it, before I decided to use HA, which brought me here.

**To Reproduce**

1. HA Side Menu -> Settings -> Automations and Scenes -> Scripts
2. Click on 'Create Script'
3. Click the '...' in the top right corner -> Edit as YAML
4. Paste the yaml for the script:

```yaml
sequence:
  - action: notify.alexa_media
    data_template:
      title: Alexa Speak...
      data:
        type: tts
      message: "{{message}}"
      target: |
        [
          {%- for key, values in targets.items() -%}
            {%- if values is string -%}
              "{{ values }}"
            {%- else -%}
              {%- for value in values -%}
                "{{ value }}"{% if not loop.last %}, {% endif %}
              {%- endfor -%}
            {%- endif %}
          {%- if not loop.last %}, {% endif %}
          {%- endfor -%}
        ]
alias: Echo talk
description: ""
fields:
  message:
    selector:
      text: null
    name: Message
    required: true
  targets:
    selector:
      target:
        entity:
          domain: media_player
          integration: alexa_media
    name: Targets
    description: Select Amazon Echo devices or areas to send your message to
    required: true
    default:
      entity_id: media_player.echo_main
mode: queued
max: 15
```

5. Save (give it a couple of seconds, otherwise it won't launch). You may see an error about the description, but that doesn't matter.
6. Again click on the ellipses of top right corner -> Run Script
7. You should be greeted with a popup similar to my screenshot above.
8. Type in any message and run some tests with indirect objects (like room or devices) as targets,
9. **I expect you won't hear anything from Alexa (the bug I refer to)**. Head back to the script editor and click on TRACES to validate that the parameters are passed in correctly.

**Expected behavior**

I expected that my message would have been spoken by all echo devices within the specified areas.

**Screenshots**

Included in the description

**System details**

- Home Assistant version: 
Core 2025.1.2
Supervisor 2024.12.3
- alexa_media version (from `const.py` or HA startup log): 5.3.0 (UI value is the same as the log)
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.5
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

```shell
2025-01-19 23:35:30.401 DEBUG (MainThread) [custom_components.alexa_media.notify] Message: test, kwargs: {'title': 'Alexa Speak...', 'target': ['office'], 'data': {'type': 'tts'}}
2025-01-19 23:35:30.401 DEBUG (MainThread) [custom_components.alexa_media.notify] Target type: <class 'homeassistant.helpers.template.gen_result_wrapper.<locals>.Wrapper'>
2025-01-19 23:35:30.401 DEBUG (MainThread) [custom_components.alexa_media.notify] Processing: office
2025-01-19 23:35:30.402 DEBUG (MainThread) [custom_components.alexa_media.notify] Processed Target by string: ['office']
```

No logs for alexapy for this action were in the output.

**Additional context**

N/A

**Comment by danielbrunt57** [comment]
AMP hooks itself into the HA `notify` platform and AMP was designed before "areas" was a thing in HA so it's no surprise that it doesn't work.

Where the wiki mentions "Guest Room", that's not an HA area but is the friendly name of an echo device or an Alexa speaker group.

**Comment by SchmidSP** [comment]
The same problem for me ( since approx. 1 week). 
Can you please check whether the groups still work for you when playing music (Amazon Music app, say “Play Music everywhere”)? For me, the groups no longer work there either. 
I therefore assume that there is a problem on the part of Amazon. 
Unfortunately, I can't find a contact at Amazon where I could report this.
I can still use the TTS on individual devices without any problems.

**Comment by digiltd** [comment]
Do you have the speaker group setup in the Alexa app? In the app go to Devices, then click the plus icon in the top right then choose Combine Speakers, then select Multi-room music, pick the Echos you want to be in the group, then choose a name and save (and apologies if you already knew how to do it, i try never to assume). The new Multi-room speaker group will then appear as its own media player in HA.

Is the idea that:

- you quickly type a message in the dashboard
- select from a list which of various Echos scattered around the house you want the message to come out of
- have the message spoken by Alexa to all the devices
  - in sync?
  - play on each device one by one, looping through the list?

**Comment by SchmidSP** [comment]
Hi,
thanks for the support first of all:

Groups are set up with the respective devices in the Alexa app (e.g. Everywhere contains all devices).

The whole thing has been used for months in various automations where notifications
 
```
Action: action: 
notify.alexa_media_uberall
data:
  message: test
```
 are sent to all devices. 
Individual devices still work.
Example:
 ```
action: notify.alexa_media_buro_2
data:
  message: test
```
Only the groups no longer do. 

I also see a http/code: 200 in log, so it look that the plugin had a clean connection to Amazon service.
POST: https://alexa.amazon.de/api/behaviors/preview returned 200:OK:application/octet-stream

I think for this project it would only be important to know if it is the HACS plugin or Amazon. 
Therefore the hint 

![Image](https://github.com/user-attachments/assets/f98c1b5d-e689-462f-8e67-697cf893f827)

that I can no longer get all devices to run simultaneously via voice control (Alexa, play music everywhere).

**Comment by danielbrunt57** [comment]
> In my case the groups I am referring to are from home assistant, so not related to amazon (in my case at least).
> 
> > so it's no surprise that it doesn't work.
> 
> It would be nice if the wiki would clarify the ambiguity of groups. As the wiki does state:
> 
> "target:" - The target Alexa devices. This can be the Friendly Name, Serial Number, entity_id, `or Home Assistant Group.` **

Home Assistant groups are not Areas.  I believe groups predate areas and were legacy entities defined in YAML.  They can now be created in the UI via Helpers:

![Image](https://github.com/user-attachments/assets/0843c379-d263-427f-b268-6de87aaf560a)

The other way woold be to create speaker group(s) in Alexa which would then be discovered by AMP as unique `media_player` device(s) for the Alexa group(s).

**Comment by danielbrunt57** [comment]
> The whole thing has been used for months in various automations where notifications
> 
> ```
> Action: action: 
> notify.alexa_media_uberall
> data:
>   message: test
> ```
> 
> are sent to all devices.

I think WHA groups only support `type: announce`?

**Comment by fabio-s-franco** [comment]
I think the most sustainable way to do this, would be to carry out the expansion, since it works with any concept of groups within HA (floors, areas, device and what not).

I will try to do it and can share here, maybe can be incorporated into the addon somehow

**Comment by SchmidSP** [comment]
Got a solution!

I changed the action in automation.

Works: 
```
actions:
  - action: notify.alexa_media
    data:
      message: Test
      data:
        type: announce
      title: Test
      target: media_player.uberall
```
Stopped Working:  
```
actions:
  - action: notify.alexa_media_uberall
    metadata: {}
    data:
      data:
        type: announce
      message: >-
        Test
 ```

So I changed my automations...

**Comment by aman-sandhu** [comment]
Announce is not working for me. tts is working fine. It used to. Not sure what changed.
Any help would be much appreciated. Thank you. I have tried the above code to no success.

**Comment by aman-sandhu** [comment]
and idiot of the year award goes to....myself....lol

tts working and announce not working solved..

For future cases: Do not disturb mode on Amazon Echo blocks Announces

**Comment by danielbrunt57** [comment]
Been there, experienced that!  Wish I had a $1 for every idiot of the year award!

**Comment by fabio-s-franco** [comment]
Nice that @aman-sandhu joined the club, but that was not really what the issue was about. The issue I reported revolves around [the notification component](https://github.com/alandtse/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service) and its ability to target HA groups:

> "target:" - The target Alexa devices. This can be the Friendly Name, Serial Number, entity_id, or **Home Assistant Group**.

As I previously mentioned, the idea of HA group can be quite ambiguous, as you can have groupings of any type. Given that expand is an actual function in HA (and can work with traditional groups, areas or entities), it is easy to assume the component takes advantage of this to be able to announce to any given scope.

To close this issue, I would say that either a patch that can resolve any type of group or a clarification in the wiki to remove the ambiguity. I haven't worked on it again yet, but it shouldn't be too difficult to make a template loop that could also be added to the wiki as a workaround to be able to target groups ubiquitously.

**Comment by oblivioncth** [comment]
Yes, the original issue still exists.

I can confirm that the notify service does not work with the newer domain specific groups you can create via the UI (helpers), but it does seem to still function with the older YAML only groups (e.g. group.my_alexa_group).

**Comment by fabio-s-franco** [comment]
I sse the tag wontfix, but I think it would not hurt a brief clarification in the wiki. Would you mind doing that, so other people understand the situation?


Also, it would be nice if the wiki had a workaround. I created one, this is a fully working example of a script I created that will expand any selector used in the target selector. Any combination of floors, areas, labels, entity (or entity groups) or devices can be selected:

```yaml
sequence:
  - action: notify.alexa_media
    data_template:
      title: Alexa Speak...
      data:
        type: tts
      message: <voice name="{{voice}}">{{ message }}</voice>
      target: >
        {%- set ns = namespace(all_targets=[]) -%} {# Normalize targets: if a
        single string, wrap it; if a mapping, flatten its values; else assume
        it’s already a list #} {%- if targets is string -%}
          {%- set ns.all_targets = [ targets ] %}
        {%- elif targets is mapping -%}
          {%- for key, value in targets.items() -%}
            {%- if value is string -%}
              {%- set ns.all_targets = ns.all_targets + [ value ] %}
            {%- elif value is iterable and value is not string -%}
              {%- set ns.all_targets = ns.all_targets + value %}
            {%- else -%}
              {%- set ns.all_targets = ns.all_targets + [ value ] %}
            {%- endif -%}
          {%- endfor -%}
        {%- else -%}
          {%- set ns.all_targets = targets | default([]) %}
        {%- endif -%}

        {# Fallback: if our normalized list is empty, use single_target (which
        may itself be a string) #} {%- if ns.all_targets | length == 0 -%}
          {%- if single_target is string -%}
            {%- set ns.all_targets = [ single_target ] %}
          {%- else -%}
            {%- set ns.all_targets = single_target | default('media_player.tablet') %}
            {%- if ns.all_targets is string -%}
              {%- set ns.all_targets = [ ns.all_targets ] %}
            {%- endif -%}
          {%- endif -%}
        {%- endif %}

        {# Derive additional identifiers from floors, areas, and labels #} {%-
        set floor_areas_list = ns.all_targets | map('floor_areas') | list |
        sum(start=[]) %} {%- set floor_area_entities = floor_areas_list |
        map('area_entities') | list | sum(start=[]) %} {%- set
        area_entities_list = ns.all_targets | map('area_entities') | list |
        sum(start=[]) %} {%- set label_entities_list = ns.all_targets |
        map('label_entities') | list | sum(start=[]) %}

        {# Combine original targets with derived ones #} {%- set combined =
        ns.all_targets + floor_area_entities + area_entities_list +
        label_entities_list %} {%- set expanded = expand(combined) | list %} {%-
        set final_media = expanded
            | selectattr("entity_id", "match", "^media_player\\.")
            | map(attribute="entity_id")
            | list %}

        [ {%- for ent in final_media -%}
          "{{ ent }}"{{ "," if not loop.last }}
        {%- endfor -%} ]
alias: Echo talk
description: ""
fields:
  message:
    selector:
      text: null
    name: Message
    required: true
  targets:
    selector:
      target:
        entity:
          domain: media_player
          integration: alexa_media
    name: Targets
    description: Select Amazon Echo devices or areas to send your message to
    required: false
    default:
      entity_id: media_player.echo_main
  voice:
    selector:
      select:
        options:
          - Ivy
          - Joanna
          - Joey
          - Justin
          - Kendra
          - Kimberly
          - Matthew
          - Salli
    name: Voice
    default: Matthew
  single_target:
    selector:
      target: {}
    name: Single target
mode: queued
max: 15

```

Probably would be helpful to other people.
