### ISSUE TITLE
Shopping List

### ISSUE THREAD

**Issue by broyuken** [alandtse/alexa_media_player#298]
Is there a way to add the shopping list functionality into HA using this? I would love a way to be able to view, add and remove items from my shopping list through HA. Currently I use Anylist which syncs with my alexa list. Is this same sort of syncing available to add as an lovelace card?

**Comment by alandtse** [comment]
Do you have an example of a HA list that would work? It's not hard to expose the list. The UI and use wouldn't be part of this component though.

**Comment by broyuken** [comment]
I was thinking the built in shopping list. That would probably work best since it’s already in HA, but I’m not sure what format the Alexa lists use. But if you can come up with a better way to accomplish this I’m all ears. I just want to get to the end result :)

**Comment by alandtse** [comment]
I'm not aware of any built in Home Assistant shopping list. Can you send me the link?

**Comment by alandtse** [comment]
Nevermind. Found [it](https://www.home-assistant.io/components/shopping_list/).

**Comment by broyuken** [comment]
awesome, let me know if I can help out in any way by testing or anything.

**Comment by alandtse** [comment]
Took a look at the built in shopping_list and it's really not designed for interaction from other components. The services that are accessible are only `add` and `complete` items with no ability to clear. There are other mechanisms to make updates but are hacky as they would require either a websockets connection or get to HASS.  It also only supports a single list where each Amazon account can have multiple.

There's actually an open [issue](https://github.com/home-assistant/appdaemon/issues/667#issuecomment-530642485) in appdaemon to try to add support for the shopping_list and it's run into the same problems I'm running into for how to actually edit it. Until the built in shopping_list is more robust, I don't think there's much worth trying to sync Alexa's list with it. 

Let me know if you see other shopping_list implementations to consider.

**Comment by broyuken** [comment]
Grocery perhaps?

**Comment by tb-killa** [comment]
@alandtse would you implement the Shopping List from Alexa themselve to provide this Informations inside HA? I think this would be the easy way because everyone could themselve build logic to push and modify data on own needing way.

**Comment by alandtse** [comment]
@tb-killa Checking if it's allowed to call the services in another component. If it's allowed, I think syncing may be possible. One other issue is I don't know if a component can actually check the actual shopping list to see what's there.

**Comment by aptonline** [comment]
Sorry to hijack this post and I releasee that nothing have changed from a HA perspective in terms on additionally functionality for the ask but you mentioned that its not hard to expose the list? would even this functionality not be useful to show within HA even though you can't interact with it?

I'm looking at placing a tablet on my fridge which is near Alexa and having the ability to see what's on my list before adding something else would be very useful.  If I remove something via Alexa I would see an instance change on the tablet. 

Yes its not as advanced as @broyuken envisaged but useful non the less.

**Comment by jampez77** [comment]
> Sorry to hijack this post and I releasee that nothing have changed from a HA perspective in terms on additionally functionality for the ask but you mentioned that its not hard to expose the list? would even this functionality not be useful to show within HA even though you can't interact with it?
> 
> I'm looking at placing a tablet on my fridge which is near Alexa and having the ability to see what's on my list before adding something else would be very useful. If I remove something via Alexa I would see an instance change on the tablet.
> 
> Yes its not as advanced as @broyuken envisaged but useful non the less.

I second this! Plus exposing the lists will allow some to develop an integration specifically for this purpose.

**Comment by shbatm** [comment]
I'd like to see this supported as well, at least just in the AlexyPy API--not necessarily trying to use it with the built-in shopping list. 

Grocy Chores are made available via the custom_component in a Home Assistant sensor with the state being a json payload of the chores list -- this lets a custom lovelace component make the formatting all pretty for display. It would also allow Automations / NodeRED / AppDaemon / PyScript automations to pickup and process the JSON payload further to do what they want with it.

The biggest benefit I see is taking advantage of the already logged-in API module to grab this data.

**Comment by alandtse** [comment]
I'll leave this open in case someone wants to implement something.

**Comment by drinfernoo** [comment]
FWIW, I use this integration: https://github.com/vlebourl/shopping_list

It works just like that standard Shopping List integration, but syncs with "Bring!". Conveniently, Bring! also integrates with both Google Home *and* Alexa, so with the right setup, you can tell Alexa "add X to the list", it will show up in your HA shopping list, and vice versa.

I know it's not exactly what was asked for, but it works for me better than any of the other solutions I've tried, and with both of the voice assistants we use in our home.

**Comment by N1c093** [comment]
Would it make sense, if we reopen this feature request/issue? 
Sadly Amazon discontinued the official API https://developer.amazon.com/en-US/docs/alexa/ask-overviews/deprecated-features.html#shopping-lists

Therefore some Apps like "todoist" can't sync the shopping list from Alexa anymore.

**Comment by broyuken** [comment]
I had been using anylist and have the same problem now. And getting my wife to remember that now we have to say "Alexa ask anylist to add eggs to the grocery list" is not easy. For now I'm basically taking stuff off the alexa grocery list and manually putting it in the HA list so it shows up on our dashboard in the kitchen but that's not a sustainable solution. Is there a way to pull this list data from the official alexa grocery lists into HA?

**Comment by JueK3y-Prv** [comment]
The same for me, plus support for shopping lists such as Blinkist is severely limited now... It would be nice if there was a direct link between the Alexa Shopping List and the HomeAssistant Shopping List

**Comment by roondar** [comment]
It could be good to integrate directly to this integration : https://github.com/roondar/alexa2ha/tree/main

**Comment by roondar** [comment]
It could be good to integrate directly to this integration : https://github.com/roondar/alexa2ha/
It can be trigger by

[alexa_media_player/custom_components/alexa_media/__init__.py](https://github.com/alandtse/alexa_media_player/blob/a6aab7e0277adc060ad9c29101ceb86cfcc5847d/custom_components/alexa_media/__init__.py#L1084)

Line 1084 in [a6aab7e](https://github.com/alandtse/alexa_media_player/commit/a6aab7e0277adc060ad9c29101ceb86cfcc5847d)

 "PUSH_LIST_ITEM_CHANGE",  # update shopping list 

Wdyt @alandtse ? :)
How to handle Alexa / HA to do list https://github.com/SavageCore/HA_Addons/blob/main/alexa_shopping_list_sync/app/classes/homeassistant_websocket.py#L72

**Comment by danielbrunt57** [comment]
> Wdyt @alandtse ? 😄
> How to handle Alexa / HA to do list : https://github.com/SavageCore/HA_Addons/blob/main/alexa_shopping_list_sync/app/classes/homeassistant_websocket.py#L72

Alan has stepped away from AMP integration development and management and is only involved in reviewing/merging submitted pull requests.  This integration is officially on life support with only a couple of contributors (myself included) trying to keep it alive.
I had a look and your suggestion certainly looks doable and I appreciate you offering the links.
For myself, when I am shopping I prefer to open the Alexa app and check off items on my shopping list but I appreciate that others may want to see their Alexa shopping list in HA so, I'll see if I can at least synchronize the Alexa shopping list with HA but for me, I would not like that the process marks the synchronized items as done in Alexa.

When I have time I'll play with it...

**Comment by danielbrunt57** [comment]
Unfortunately, the "PUSH_LIST_ITEM_CHANGE" directive seems to no longer be pushed by Amazon via http2push when I say "Alexa, add lettuce to my shopping list" as I'm not seeing a log entry...
```
                elif command == "PUSH_LIST_ITEM_CHANGE",  # update shopping list:
                    _LOGGER.debug("PUSH_ITEM_LIST_CHANGE: %s", json_payload)
                
                elif command in [
                    "PUSH_DELETE_DOPPLER_ACTIVITIES",  # delete Alexa history
                    "PUSH_LIST_CHANGE",  # clear a shopping list https://github.com/alandtse/alexa_media_player/issues/1190
                    "PUSH_CONTENT_FOCUS_CHANGE",  # likely prime related refocus
                    "PUSH_DEVICE_SETUP_STATE_CHANGE",  # likely device changes mid setup
                    "PUSH_MEDIA_PREFERENCE_CHANGE",  # disliking or liking songs, https://github.com/alandtse/alexa_media_player/issues/1599
                ]:
                    pass
```
I'm afraid it's joined the defunct commands along with PUSH_ACTIVITY, which last_alexa relied upon...

**Comment by roondar** [comment]
> > Wdyt @alandtse ? 😄
> > How to handle Alexa / HA to do list : https://github.com/SavageCore/HA_Addons/blob/main/alexa_shopping_list_sync/app/classes/homeassistant_websocket.py#L72
> 
> Alan has stepped away from AMP integration development and management and is only involved in reviewing/merging submitted pull requests. This integration is officially on life support with only a couple of contributors (myself included) trying to keep it alive. I had a look and your suggestion certainly looks doable and I appreciate you offering the links. For myself, when I am shopping I prefer to open the Alexa app and check off items on my shopping list but I appreciate that others may want to see their Alexa shopping list in HA so, I'll see if I can at least synchronize the Alexa shopping list with HA but for me, I would not like that the process marks the synchronized items as done in Alexa.
> 
> When I have time I'll play with it...

Sure, I understand.
Let me know if I Can help on it.

**Comment by roondar** [comment]
> Unfortunately, the "PUSH_LIST_ITEM_CHANGE" directive seems to no longer be pushed by Amazon via http2push when I say "Alexa, add lettuce to my shopping list" as I'm not seeing a log entry...
> 
> ```
>                 elif command == "PUSH_LIST_ITEM_CHANGE",  # update shopping list:
>                     _LOGGER.debug("PUSH_ITEM_LIST_CHANGE: %s", json_payload)
>                 
>                 elif command in [
>                     "PUSH_DELETE_DOPPLER_ACTIVITIES",  # delete Alexa history
>                     "PUSH_LIST_CHANGE",  # clear a shopping list https://github.com/alandtse/alexa_media_player/issues/1190
>                     "PUSH_CONTENT_FOCUS_CHANGE",  # likely prime related refocus
>                     "PUSH_DEVICE_SETUP_STATE_CHANGE",  # likely device changes mid setup
>                     "PUSH_MEDIA_PREFERENCE_CHANGE",  # disliking or liking songs, https://github.com/alandtse/alexa_media_player/issues/1599
>                 ]:
>                     pass
> ```
> 
> I'm afraid it's joined the defunct commands along with PUSH_ACTIVITY, which last_alexa relied upon...

Weird because for me it was working.

**Comment by danielbrunt57** [comment]
> Weird because for me it was working.

What was working????

**Comment by roondar** [comment]
I had the push events when I was asking Alexa to add something in my basket.

**Comment by danielbrunt57** [comment]
I found an issue in my edit and am now seeing the push command:
```
2024-08-24 12:47:35.244 DEBUG (MainThread) [custom_components.alexa_media] PUSH_ITEM_LIST_CHANGE: {'listId': 'YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=', 'listItemId': 'f933e216-fdbc-4f67-ad59-519dc73721d4', 'version': 1, 'eventName': 'itemCreated', 'destinationUserId': 'A1UZ93DGNU3F5L'}
```
It will take me a while to get from this to something functional and right now I don't have any spare time...

**Comment by roondar** [comment]
> I found an issue in my edit and am now seeing the push command:
> 
> ```
> 2024-08-24 12:47:35.244 DEBUG (MainThread) [custom_components.alexa_media] PUSH_ITEM_LIST_CHANGE: {'listId': 'YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=', 'listItemId': 'f933e216-fdbc-4f67-ad59-519dc73721d4', 'version': 1, 'eventName': 'itemCreated', 'destinationUserId': 'A1UZ93DGNU3F5L'}
> ```
> 
> It will take me a while to get from this to something functional and right now I don't have any spare time...

May be you can open a new branch and I'll check what you'll push. :muscle:

**Comment by danielbrunt57** [comment]
I've managed to add a `hass.bus.async_fire` event to that push command and this is the event that fired:
```
event_type: alexa_media_shopping_list_event
data:
  event: itemUpdated
  list: YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=
  item: 144d014f-2454-42f4-ac26-d985d6ed83d7
  user: A1UZ93DGNU3F5L
origin: LOCAL
time_fired: "2024-09-07T10:33:45.868533+00:00"
context:
  id: 01J760R1MC1XR5SA60TM7YDA6D
  parent_id: null
  user_id: null
```
My code change:
```
                    case "PUSH_LIST_CHANGE":
                        # Clear a shopping list (https://github.com/alandtse/alexa_media_player/issues/1190)
                        _LOGGER.debug("http2push: Shopping list - Clear")
                        hass.bus.async_fire(
                            "alexa_media_shopping_list_event",
                            {
                                "event": json_payload["eventName"],
                                "payload": json_payload,
                            }
                        )

                    case "PUSH_LIST_ITEM_CHANGE":
                        # Update shopping list
                        _LOGGER.debug("http2push: Shopping list - Update")
                        hass.bus.async_fire(
                            "alexa_media_shopping_list_event",
                            {
                                "event": json_payload["eventName"],
                                "list": json_payload["listId"],
                                "item": json_payload["listItemId"],
                                "user": json_payload["destinationUserId"],
                            }
                        )
```
Next step will be to see how to integrate that into the [Alexa to Home Assistant Shopping List Sync]( https://github.com/roondar/alexa2ha/)

**Comment by danielbrunt57** [comment]
These HTTP2PUSH commands aren't going to be terribly useful as they contain no other information other than that ItemId was updated.  
If I add an item I get a push that ItemID xyz was updated.  
If I remove that item then there's another push that ItemId xyz was updated.  
If I add that same item item again there's a push that ItemId pqr was updated.  
Then if I re-delete that item there's a push that ItemId pqr was updated.  
And that's it!  
So the only purpose I can see for this is to maybe inform/trigger the other integration to scan and do it's thing rather than having periodic scheduled scans.

I recall having seen another integration that can add items to the Alexa Shopping List (via a zero volume TTS command to an echo device).  Ideally, it would be nice to have AMP's HTTP2PUSH connection as an instant trigger that the Alexa side was changed and then combine parts of [Alexa to Home Assistant Shopping List Sync](https://github.com/roondar/alexa2ha/) and that other integration I mentioned to have a fully integrated HA Shopping List that is a mirrored copy of the Alexa Shopping List and has two-way sync between them.  But that is a huge wishlist...

**Comment by danielbrunt57** [comment]
```
event_type: alexa_media_shopping_list_event
data:
  event: itemUpdated
  list: YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=
  item: a2a2bb52-ed14-4103-bb65-70c870e88752
  user: A1UZ93DGNU3F5L
origin: LOCAL
time_fired: "2024-09-07T10:51:01.304736+00:00"
context:
  id: 01J761QMSRX56N8KTD206FH823
  parent_id: null
  user_id: null
```
```
event_type: alexa_media_shopping_list_event
data:
  event: itemCreated
  list: YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=
  item: 62663c6e-3efa-4757-9fc8-f6c33ead5f75
  user: A1UZ93DGNU3F5L
origin: LOCAL
time_fired: "2024-09-07T10:51:11.369054+00:00"
context:
  id: 01J761QYM9BQQV831JGPAWE1SM
  parent_id: null
  user_id: null
```
```
event_type: alexa_media_shopping_list_event
data:
  event: itemUpdated
  list: YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=
  item: 62663c6e-3efa-4757-9fc8-f6c33ead5f75
  user: A1UZ93DGNU3F5L
origin: LOCAL
time_fired: "2024-09-07T10:51:37.660234+00:00"
context:
  id: 01J761RR9WXR8JGDXQ56N38XCT
  parent_id: null
  user_id: null
```
```
event_type: alexa_media_shopping_list_event
data:
  event: itemCreated
  list: YW16bjEuYWNjb3VudC5BRU9YVTJGNEFVWlg2SFI0Wk1WVEtGMldRNkpBLVNIT1BQSU5HX0lURU0=
  item: 293126be-9b64-4b6f-9225-ae29a9972a51
  user: A1UZ93DGNU3F5L
origin: LOCAL
time_fired: "2024-09-07T10:51:50.629150+00:00"
context:
  id: 01J761S4Z5DBRJZYN374VC69XT
  parent_id: null
  user_id: null
```
